[package]
name = "volume"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.11.4"
rust-pulsectl-fork = "0.2.12"
libpulse-binding = "2.26.0"
